### ISSUE TITLE
Set up express server

### ISSUE THREAD

**Issue by faisal244** [faisal244/eco-bike-hire#1]
### Tasks

- [x] Brainstorm routes and information architecture as a team
- [x] add files and folders
- [x] Add express server boilerplate to each file
- [x] Define routes
- [x] Name controller functions
- [x] Set up controller files and folders
